DROP DATABASE IF EXISTS DB_SHOP;
CREATE SCHEMA IF NOT EXISTS DB_SHOP;
USE DB_SHOP;
CREATE TABLE IF NOT EXISTS CUSTOMERS(
    ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    SURNAME VARCHAR(255),
    BIRTHDATE VARCHAR(255),
    PHONE VARCHAR(50),
    COUNTRY VARCHAR(50),
    CITY VARCHAR(50),
    DIRECTION VARCHAR(50),
    POST_CODE VARCHAR(50)	);
INSERT INTO CUSTOMERS (NAME, SURNAME, BIRTHDATE, PHONE, COUNTRY, CITY, DIRECTION, POST_CODE)
VALUES 	('Jorge', 'Lorenzo', '1991/02/13', '66666666', 'SPAIN', 'Girona', 'Calle Girona', '1234'),
('Marc', 'Marquéz', '1989/01/22', '66666666', 'SPAIN', 'Barcelona', 'Calle Barcelona 12 1º Esc D.', '1234');
SELECT * FROM CUSTOMERS;